CREATE DATABASE codeeasy CHARACTER SET utf8 COLLATE utf8_general_ci;

USE codeeasy;

CREATE TABLE loja(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100)NOT NULL,
  telefone VARCHAR(13) NOT NULL,
  endereco VARCHAR(200) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE produtos (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  loja_id INT UNSIGNED NOT NULL,
  nome VARCHAR(100) NOT NULL,
  preco DECIMAL NOT NULL,
  quantidade INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_produtos_loja_id_lojas_id
  FOREIGN KEY (loja_id) REFERENCES lojas(id)
  );

  CREATE TABLE usuarios (
   id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(200) NOT NULL,
  email VARCHAR(200) UNIQUE NOT NULL,
  senha VARCHAR(200) NOT NULL
  );

CREATE TABLE tokes(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  usuarios_id INT UNSIGNED NOT NULL,
  token VARCHAR(1000) NOT NULL,
  refresh_token VARCHAR (1000) NOT NULL,
  expired_at DATETIME NOT NULL,
  CONSTRAINT fk_tokens_usuarios_id_usuarios_id
  FOREIGN KEY (usuarios_id) REFERENCES usuarios(id)
  );